---
cuda:
  apt:
    package: cuda=11.* # known good with 10.0.130-1
    repo: cuda-11-3_11.3.1-1_amd64.deb # Network install
    dependency: cuda-runtime-11-3_11.3.1-1_amd64.deb
    signing_key_url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub

general:
  working_dir: /tmp
